# Generated by Django 4.2.1 on 2023-05-20 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='head_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته محصول')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی اصلی محصولات',
                'db_table': 'head_products',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.head_products', verbose_name='دسته بندی اصلی محصول')),
            ],
            options={
                'verbose_name_plural': 'محصولات',
                'db_table': 'products',
            },
        ),
    ]
