# Generated by Django 4.2.1 on 2023-05-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='آدرس محصول'),
        ),
    ]
