# Generated by Django 4.2.1 on 2023-05-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_type_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type_product',
            field=models.CharField(blank=True, choices=[('.filter-app', 'تابلو'), ('.filter-card', 'پمپ')], max_length=20, null=True, verbose_name='نوع محصول '),
        ),
    ]
