# Generated by Django 4.2.1 on 2023-05-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_products_type_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type_product',
            field=models.CharField(blank=True, choices=[('col-lg-4 col-md-6 portfolio-item filter-app', 'تابلو'), ('col-lg-4 col-md-6 portfolio-item filter-card', 'پمپ')], max_length=50, null=True, verbose_name='نوع محصول '),
        ),
    ]
