# Generated by Django 4.2.1 on 2023-05-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_type_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام عکس ')),
                ('sentence', models.CharField(blank=True, max_length=300, null=True, verbose_name='جمله مورد نظر برای  صفحه اول وبسایت ')),
                ('picture', models.FileField(blank=True, null=True, upload_to='Image_First_Page/', verbose_name='عکس صفحه اول وبسایت ')),
            ],
            options={
                'verbose_name_plural': 'عکس های صفحه اولیه وبسایت ',
                'db_table': 'Hero_section',
            },
        ),
    ]
