# Generated by Django 4.2.1 on 2023-05-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_hero_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=300, null=True, verbose_name='سوال')),
                ('answer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='جواب')),
            ],
            options={
                'verbose_name_plural': 'سوالات متداول',
                'db_table': 'Frequency_questions',
            },
        ),
    ]
