# Generated by Django 4.2.1 on 2023-05-24 22:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_frequency_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency_questions',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='جواب'),
        ),
    ]
