# Generated by Django 4.2.1 on 2023-05-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_frequency_questions_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency_questions',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='جواب'),
        ),
    ]
