# Generated by Django 4.2.1 on 2023-05-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_frequency_questions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100, verbose_name='اسم کامل')),
                ('level', models.CharField(choices=[('Leader', 'مدیر عامل'), ('client', 'کارمند')], max_length=100, verbose_name='سمت فرد')),
                ('picture', models.FileField(blank=True, null=True, upload_to='Image_Team_Member/', verbose_name='عکس افراد')),
            ],
            options={
                'verbose_name_plural': 'اعضا',
                'db_table': 'Team_Member',
            },
        ),
    ]
