# Generated by Django 4.2.1 on 2023-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس لینکدین'),
        ),
    ]
