# Generated by Django 4.2.1 on 2023-05-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name_plural': 'خبرنامه',
                'db_table': 'Newsletter',
            },
        ),
    ]
