# Generated by Django 4.2.1 on 2023-05-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='email_member',
        ),
    ]
