# Generated by Django 4.2.1 on 2023-06-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture2',
            field=models.FileField(blank=True, null=True, upload_to='Products_Image', verbose_name='عکس 2 محصول '),
        ),
        migrations.AddField(
            model_name='products',
            name='picture3',
            field=models.FileField(blank=True, null=True, upload_to='Products_Image', verbose_name='عکس 3 محصول '),
        ),
    ]
