# Generated by Django 4.2.1 on 2023-06-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_products_picture2_products_picture3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_original_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100, verbose_name='سر تیتر ')),
                ('body', models.TextField(verbose_name='متن ')),
            ],
            options={
                'verbose_name_plural': 'متن برای صفحه اصلی ',
                'db_table': 'Text_original_page',
            },
        ),
    ]
