# Generated by Django 4.2.1 on 2023-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_text_original_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_original_page',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره '),
        ),
    ]
