# Generated by Django 4.2.1 on 2023-06-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_text_original_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس اینستاگرام'),
        ),
    ]
