# Generated by Django 4.2.1 on 2023-05-24 20:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام خدمت')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس خدمت ')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات خدمت')),
                ('picture', models.FileField(blank=True, null=True, upload_to='Image_Services', verbose_name='عکس خدمت')),
                ('status', models.CharField(choices=[('a', 'فعال'), ('d', 'غیر فعال ')], max_length=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name_plural': 'خدمات',
                'db_table': 'services',
            },
        ),
    ]
