# Generated by Django 4.2.1 on 2023-05-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='type_service',
            field=models.CharField(blank=True, choices=[('moshavereh', 'مشاوره'), ('design', 'طراحی'), ('install', 'نصب'), ('repair', 'تعمیرات'), ('make', 'ساخت')], max_length=15, null=True, verbose_name='نوع خدمت'),
        ),
    ]
