# Generated by Django 4.2.1 on 2023-05-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_type_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='type_service',
            field=models.CharField(blank=True, choices=[('bi bi-chat-left-dots', 'مشاوره'), ('design', 'طراحی'), ('install', 'نصب'), ('repair', 'تعمیرات'), ('make', 'ساخت')], max_length=50, null=True, verbose_name='نوع خدمت'),
        ),
    ]
